version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bor
      POSTGRES_PASSWORD: borpass
      POSTGRES_DB: bormining
    ports:
      - "5432:5432"
    volumes:
      - bor_db:/var/lib/postgresql/data
volumes:
  bor_db: